### ISSUE TITLE
Loadable-component doesn't have any stratgies for prefetching

### ISSUE THREAD

**Issue by MortezaT** [wellyshen/react-cool-starter#197] opened 2018-09-30 11:47 UTC
### Do you want to report a bug or request a feature?
React cool starter uses `loadable-components` which [doesn't support prefetch of chunks](https://github.com/smooth-code/loadable-components/issues/77) in `SSR` and there is no future target towrad it.

### Expected Behavior
Replacing package with `react-loadable` would be beneficiary

### Actual Behavior
In `SSR` page rendering takes place with out any related styles which results in FOUC.

**Comment by saeedseyfi** [comment] 2018-09-30 14:58
I have the same issue(FOUC) with my loadable components.
Please advise.

**Comment by wellyshen** [comment] 2018-10-01 15:38
@MortezaT I'll take time to consider about it, thanks

**Comment by Rid** [comment] 2018-10-29 15:59
I'm wondering if this is going to get merged soon? I'm holding out doing a big merge into my own existing project pending the outcome here, as I don't want to have to change everything twice 👍

**Comment by wellyshen** [comment] 2018-10-30 12:50
@Rid There's an [error](https://github.com/wellyshen/react-cool-starter/pull/198#issuecomment-427585030) in development. I can't find the root cause at this moment. I recommend you keep use `loadable-component` with this starter for now.

**Comment by Rid** [comment] 2018-11-01 17:48
@wellyshen @MortezaT The error should be fixed in #203, I found a couple issues:

1. We were forcing the dev env to do a fetch every time for the data, meaning the initial state was reset, this caused a loading page to appear when the data was loaded on the client (causing a mismatch between server and client renders)
2. The bundles included in the `renderHtml.js` were not correct, we were just passing `main.js` and `main.css` for the dev env. I've made it pass the correct bundles and loaded the chunks first so we get only the required code which is loaded on the server first.

Let me know why we were doing 1. as it may have some implications in the hot reload for actions (I did notice the comment there).

**Comment by Rid** [comment] 2018-11-02 11:05
It looks like https://github.com/smooth-code/loadable-components/issues/77 has been closed now as fixed, so apparently preloading works in `loadable-components`, I'll play around and get it working.

In terms of which library to use, `react-loadable` is no longer accepting issues, so I'm not sure if it's being actively maintained?

@wellyshen what's your opinion? I'm happy to make a PR as well for `loadable-components` with preloading.

**Comment by Rid** [comment] 2018-11-02 16:34
I have tried updating https://github.com/smooth-code/loadable-components to v4, however I have some issues https://github.com/smooth-code/loadable-components/issues/135.

My branch if you'd like to test is here: https://github.com/Rid/react-cool-starter/tree/feature/loadable-components-v4.

**Comment by MortezaT** [comment] 2018-11-10 18:49
@wellyshen 
I think it would be great if we have `SSR` only i developement since it cause lots of problems while developing like unwanted ans unrealistic errors and you have to rebuild the source for server most of the time.
But if you remove it from development mode both issues will solve the same time.

**Closed as completed** 2018-11-12 14:45 UTC
